from extensions.graph import Node, Edge, Color, TrackType
from extensions.cards import Ticket


class InvalidGame(Exception):
    "Raised when map name is not recognised."
    pass


class Map():
    def __init__(self, map: str):
        """ Class for representing a map. """
        self.nodes = []
        self.edges = []
        self.tickets = []

        if map.lower() == "europe":
            self.init_europe()
        else:
            raise InvalidGame(f"Map not recognised: {map}")
    
    def __repr__(self):
        return self.name


    def init_europe(self):
        """ Initiates the map of Ticket to Ride: Europe. """
        self.name = "Europe"

        # Nodes
        lisbon = Node("Lisbon", add_to = self.nodes)
        cadiz = Node("Cádiz", add_to = self.nodes)
        madrid = Node("Madrid", add_to = self.nodes)
        pamplona = Node("Pamplona", add_to = self.nodes)
        barcelona = Node("Barcelona", add_to = self.nodes)
        paris = Node("Paris", add_to = self.nodes)
        dieppe = Node("Dieppe", add_to = self.nodes)
        brest = Node("Brest", add_to = self.nodes)
        london = Node("London", add_to = self.nodes)
        edinburgh = Node("Edinburgh", add_to = self.nodes)
        amsterdam = Node("Amsterdam", add_to = self.nodes)
        bruxelles = Node("Bruxelles", add_to = self.nodes)
        essen = Node("Essen", add_to = self.nodes)
        zurich = Node("Zürich", add_to = self.nodes)
        marseille = Node("Marseille", add_to = self.nodes)
        frankfurt = Node("Frankfurt", add_to = self.nodes)
        munchen = Node("München", add_to = self.nodes)
        venezia = Node("Venezia", add_to = self.nodes)
        roma = Node("Roma", add_to = self.nodes)
        palermo = Node("Palermo", add_to = self.nodes)
        berlin = Node("Berlin", add_to = self.nodes)
        kobenhavn = Node("København", add_to = self.nodes)
        stockholm = Node("Stockholm", add_to = self.nodes)
        wien = Node("Wien", add_to = self.nodes)
        zagreb = Node("Zagreb", add_to = self.nodes)
        sarajevo = Node("Sarajevo", add_to = self.nodes)
        brindisi = Node("Brindisi", add_to = self.nodes)
        athina = Node("Athína", add_to = self.nodes)
        sofia = Node("Sofia", add_to = self.nodes)
        budapest = Node("Budapest", add_to = self.nodes)
        warszawa = Node("Warszawa", add_to = self.nodes)
        danzig = Node("Danzig", add_to = self.nodes)
        riga = Node("Rīga", add_to = self.nodes)
        petrograd = Node("Petrograd", add_to = self.nodes)
        vilnius = Node("Vilnius", add_to = self.nodes)
        smolensk = Node("Smolensk", add_to = self.nodes)
        kyiv = Node("Kyiv", add_to = self.nodes)
        moskva = Node("Moskva", add_to = self.nodes)
        bucuresti = Node("București", add_to = self.nodes)
        sevastopol = Node("Sevastopol", add_to = self.nodes)
        constantinople = Node("Constantinople", add_to = self.nodes)
        smyrna = Node("Smyrna", add_to = self.nodes)
        angora = Node("Angora", add_to = self.nodes)
        erzurum = Node("Erzurum", add_to = self.nodes)
        sochi = Node("Sochi", add_to = self.nodes)
        rostov = Node("Rostóv", add_to = self.nodes)
        kharkiv = Node("Kharkiv", add_to = self.nodes)

        # Edges
        self.edges.append(Edge([lisbon, cadiz], Color.blue, 2))
        self.edges.append(Edge([lisbon, madrid], Color.pink, 3))
        self.edges.append(Edge([cadiz, madrid], Color.orange, 3))
        self.edges.append(Edge([madrid, barcelona], Color.yellow, 2))
        self.edges.append(Edge([madrid, pamplona], Color.black, 3, track_type=TrackType.tunnel))
        self.edges.append(Edge([madrid, pamplona], Color.white, 3, track_type=TrackType.tunnel))
        self.edges.append(Edge([barcelona, pamplona], Color.grey, 2, track_type=TrackType.tunnel))
        self.edges.append(Edge([barcelona, marseille], Color.grey, 4))
        self.edges.append(Edge([pamplona, marseille], Color.red, 4))
        self.edges.append(Edge([pamplona, paris], Color.blue, 4))
        self.edges.append(Edge([pamplona, paris], Color.green, 4))
        self.edges.append(Edge([pamplona, brest], Color.pink, 4))
        self.edges.append(Edge([brest, paris], Color.black, 3))
        self.edges.append(Edge([brest, dieppe], Color.orange, 2))
        self.edges.append(Edge([paris, dieppe], Color.pink, 1))
        self.edges.append(Edge([dieppe, london], Color.grey, 2, locomotive_count=1))
        self.edges.append(Edge([dieppe, london], Color.grey, 2, locomotive_count=1))
        self.edges.append(Edge([dieppe, bruxelles], Color.green, 2))
        self.edges.append(Edge([dieppe, london], Color.grey, 2, locomotive_count=1))
        self.edges.append(Edge([dieppe, london], Color.grey, 2, locomotive_count=1))
        self.edges.append(Edge([london, amsterdam], Color.grey, 2, locomotive_count=2))
        self.edges.append(Edge([london, edinburgh], Color.black, 4))
        self.edges.append(Edge([london, edinburgh], Color.orange, 4))
        self.edges.append(Edge([paris, bruxelles], Color.yellow, 2))
        self.edges.append(Edge([paris, bruxelles], Color.red, 2))
        self.edges.append(Edge([bruxelles, amsterdam], Color.black, 1))
        self.edges.append(Edge([amsterdam, essen], Color.yellow, 3))
        self.edges.append(Edge([amsterdam, frankfurt], Color.white, 2))
        self.edges.append(Edge([bruxelles, frankfurt], Color.blue, 2))
        self.edges.append(Edge([paris, frankfurt], Color.white, 3))
        self.edges.append(Edge([paris, frankfurt], Color.orange, 3))
        self.edges.append(Edge([paris, zurich], Color.grey, 3, track_type=TrackType.tunnel))
        self.edges.append(Edge([paris, marseille], Color.grey, 4))
        self.edges.append(Edge([marseille, roma], Color.grey, 4, track_type=TrackType.tunnel))
        self.edges.append(Edge([marseille, zurich], Color.pink, 2, track_type=TrackType.tunnel))
        self.edges.append(Edge([zurich, venezia], Color.green, 2, track_type=TrackType.tunnel))
        self.edges.append(Edge([zurich, munchen], Color.yellow, 2, track_type=TrackType.tunnel))
        self.edges.append(Edge([munchen, venezia], Color.blue, 2, track_type=TrackType.tunnel))
        self.edges.append(Edge([venezia, roma], Color.black, 2))
        self.edges.append(Edge([frankfurt, munchen], Color.pink, 2))
        self.edges.append(Edge([frankfurt, essen], Color.green, 2))
        self.edges.append(Edge([frankfurt, berlin], Color.black, 3))
        self.edges.append(Edge([frankfurt, berlin], Color.red, 3))
        self.edges.append(Edge([essen, berlin], Color.blue, 2))
        self.edges.append(Edge([essen, kobenhavn], Color.grey, 3, locomotive_count=1))
        self.edges.append(Edge([essen, kobenhavn], Color.grey, 3, locomotive_count=1))
        self.edges.append(Edge([kobenhavn, stockholm], Color.yellow, 3))
        self.edges.append(Edge([kobenhavn, stockholm], Color.white, 3))
        self.edges.append(Edge([roma, palermo], Color.grey, 4, locomotive_count=1))
        self.edges.append(Edge([roma, brindisi], Color.white, 2))
        self.edges.append(Edge([palermo, brindisi], Color.grey, 3, locomotive_count=1))
        self.edges.append(Edge([brindisi, athina], Color.grey, 4, locomotive_count=1))
        self.edges.append(Edge([palermo, smyrna], Color.grey, 6, locomotive_count=2))
        self.edges.append(Edge([sarajevo, athina], Color.green, 4))
        self.edges.append(Edge([sofia, athina], Color.pink, 3))
        self.edges.append(Edge([sarajevo, sofia], Color.grey, 2, track_type=TrackType.tunnel))
        self.edges.append(Edge([zagreb, sarajevo], Color.red, 3))
        self.edges.append(Edge([sarajevo, budapest], Color.pink, 3))
        self.edges.append(Edge([venezia, zagreb], Color.grey, 2))
        self.edges.append(Edge([munchen, wien], Color.orange, 3))
        self.edges.append(Edge([wien, zagreb], Color.grey, 2))
        self.edges.append(Edge([zagreb, budapest], Color.orange, 2))
        self.edges.append(Edge([wien, budapest], Color.red, 1))
        self.edges.append(Edge([wien, budapest], Color.white, 1))
        self.edges.append(Edge([berlin, wien], Color.green, 3))
        self.edges.append(Edge([wien, warszawa], Color.blue, 4))
        self.edges.append(Edge([berlin, warszawa], Color.pink, 4))
        self.edges.append(Edge([berlin, warszawa], Color.yellow, 4))
        self.edges.append(Edge([berlin, danzig], Color.grey, 4))
        self.edges.append(Edge([danzig, warszawa], Color.grey, 2))
        self.edges.append(Edge([danzig, riga], Color.black, 3))
        self.edges.append(Edge([stockholm, petrograd], Color.grey, 8, track_type=TrackType.tunnel))
        self.edges.append(Edge([riga, petrograd], Color.grey, 4))
        self.edges.append(Edge([riga, vilnius], Color.green, 4))
        self.edges.append(Edge([warszawa, vilnius], Color.red, 3))
        self.edges.append(Edge([warszawa, kyiv], Color.grey, 4))
        self.edges.append(Edge([budapest, kyiv], Color.grey, 6, track_type=TrackType.tunnel))
        self.edges.append(Edge([budapest, bucuresti], Color.grey, 4, track_type=TrackType.tunnel))
        self.edges.append(Edge([sofia, bucuresti], Color.grey, 2, track_type=TrackType.tunnel))
        self.edges.append(Edge([sofia, constantinople], Color.blue, 3))
        self.edges.append(Edge([bucuresti, constantinople], Color.yellow, 3))
        self.edges.append(Edge([athina, smyrna], Color.grey, 2, locomotive_count=1))
        self.edges.append(Edge([smyrna, constantinople], Color.grey, 2, track_type=TrackType.tunnel))
        self.edges.append(Edge([smyrna, angora], Color.orange, 3, track_type=TrackType.tunnel))
        self.edges.append(Edge([constantinople, angora], Color.grey, 2, track_type=TrackType.tunnel))
        self.edges.append(Edge([angora, erzurum], Color.black, 3))
        self.edges.append(Edge([constantinople, sevastopol], Color.grey, 4, locomotive_count=2))
        self.edges.append(Edge([sevastopol, erzurum], Color.grey, 4, locomotive_count=2))
        self.edges.append(Edge([sochi, erzurum], Color.red, 3, track_type=TrackType.tunnel))
        self.edges.append(Edge([sevastopol, sochi], Color.grey, 2, locomotive_count=1))
        self.edges.append(Edge([rostov, sochi], Color.grey, 2))
        self.edges.append(Edge([sevastopol, rostov], Color.grey, 4))
        self.edges.append(Edge([kharkiv, rostov], Color.green, 2))
        self.edges.append(Edge([bucuresti, sevastopol], Color.white, 4))
        self.edges.append(Edge([bucuresti, kyiv], Color.grey, 4))
        self.edges.append(Edge([kyiv, kharkiv], Color.grey, 4))
        self.edges.append(Edge([kharkiv, moskva], Color.grey, 4))
        self.edges.append(Edge([kyiv, smolensk], Color.red, 3))
        self.edges.append(Edge([vilnius, kyiv], Color.grey, 2))
        self.edges.append(Edge([vilnius, smolensk], Color.yellow, 3))
        self.edges.append(Edge([smolensk, moskva], Color.orange, 2))
        self.edges.append(Edge([vilnius, petrograd], Color.blue, 4))
        self.edges.append(Edge([petrograd, moskva], Color.white, 4))

        # Tickets
        self.tickets.append(Ticket(cadiz, stockholm, 21))  # NOTE: Check this one

